New updates to configs

diff --git a/dev-env b/dev-env
--- a/dev-env
+++ b/dev-env
@@ -41,27 +41,50 @@ ensure_git_installed() {
     echo "git is installed."
 }
 
+install_packages() {
+    PACKAGE_FILE=./package_list.txt
+    if [ ! -f $PACKAGE_FILE ]; then
+        echo "Package list file not found, what the fuck just happened."
+        exit 1
+    else
+        for package in $(cat $PACKAGE_FILE); do
+            install_package $package
+        done
+    fi
+}
+
+clone_dev_repo() {
+    mkdir dev-env-stage
+    cd dev-env-stage
+    git clone https://github.com/wellatleastitried/dev-env.git || echo "Failed to clone dev-env from Github..." && exit 1
+    cp -r ./dev-env/* .
+    DEV_ENV_PATH=$(pwd)
+}
+
+install_xnote() {
+    cd /tmp
+    git clone https://github.com/wellatleastitried/xnote.git
+    cd xnote
+    sudo install xnote
+    cd $DEV_ENV_PATH
+}
+
+ensure_tools_installed() {
+    if ! which xnote; then
+        install-xnote
+    fi
+}
+
 ensure_repo_cloned() {
     echo "Checking if inside dev-env repository..."
     if ! grep -q "f3bbd53a6dac5aa71fdad71cad50bc1db0b2409d394a5206a4933d6f8c34bd06" .dev-env-hash; then
         echo "dev-env not found: cloning repo"
-        mkdir dev-env-stage
-        cd dev-env-stage
-        git clone https://github.com/wellatleastitried/dev-env.git || echo "Failed to clone dev-env from Github..." && exit 1
-        cp -r ./dev-env/* .
-        DEV_ENV_PATH=$(pwd)
+        clone_dev_repo
         if ! grep -q "PATH_DEV_ENV" ~/.bashrc; then
             echo "export PATH_DEV_ENV=$DEV_ENV_PATH" >> ~/.bashrc
         fi
-        PACKAGE_FILE=./package_list.txt
-        if [ ! -f $PACKAGE_FILE ]; then
-            echo "Package list file not found, what the fuck just happened."
-            exit 1
-        else
-            for package in $(cat $PACKAGE_FILE); do
-                install_package $package
-            done
-        fi
+        install_packages
+        ensure_tools_installed
     else
         DEV_ENV_PATH="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
     fi
@@ -92,6 +115,15 @@ renew_nvim_config() {
     mkdir -p ~/.config
     cp -r "$DEV_ENV_PATH/config/nvim" ~/.config/
     echo "nvim config renewed."
+    HOOKS_DIR="$HOME/.config/omarchy/hooks"
+    if [ -d "$HOOKS_DIR" ]; then
+        if [ ! -f "$HOOKS_DIR/theme-set" ]; then
+            echo "Creating theme-set hook for Omarchy..."
+            cp "$HOOKS_DIR/theme-set.sample" "$HOOKS_DIR/theme-set"
+            sudo echo "ln -sf \"\$HOME/.config/omarchy/current/theme/neovim.lua\" \"\$HOME/.config/nvim/lua/plugins/theme.lua\"" >> "$HOOKS_DIR/theme-set"
+        fi
+    fi
+
 }
 
 renew_configs() {
